version: "3.5"
services:
  headscale:
    image: headscale/headscale:latest
    volumes:
      - ./config:/etc/headscale/
      - ./data:/var/lib/headscale
    ports:
      - 27896:8080
    command: headscale serve
    restart: unless-stopped

  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    environment:
      - TZ=Europe/London
      - PGID=1000
      - PUID=1000
      - COLOR=blue                              # Use the base colors (ie, no darken-3, etc) -
      - HS_SERVER=https://headscale.inthearea.party    # Reachable endpoint for your Headscale server
      - DOMAIN_NAME=https://headscale.inthearea.party  # The base domain name for this container.
      - SCRIPT_NAME=/admin                     # This is your applications base path (wsgi requires the name "SCRIPT_NAME").  Remove if you are hosing at the root /
      - KEY="KrBdaxuwf0q2kEXBdK1WBtcKQo0gS762x1NAJInUfL4="             # Generate with "openssl rand -base64 32" - used to encrypt your key on disk.
      - AUTH_TYPE=oidc                         # AUTH_TYPE is either Basic or OIDC.  Empty for no authentication
      - LOG_LEVEL=info                         # Log level.  "DEBUG", "ERROR", "WARNING", or "INFO".  Default "INFO"
      # ENV for Basic Auth (Used only if AUTH_TYPE is "Basic").  Can be omitted if you aren't using Basic Auth
      #- BASIC_AUTH_USER=daniel                   # Used for basic auth
      #- BASIC_AUTH_PASS=Sh3ff0rd                 # Used for basic auth
      # ENV for OIDC (Used only if AUTH_TYPE is "OIDC").  Can be omitted if you aren't using OIDC
      - OIDC_AUTH_URL=https://dashboard-auth.inthearea.party/application/o/headscale-ui/.well-known/openid-configuration # URL for your OIDC issuer's well-known endpoint
      - OIDC_CLIENT_ID=pm2OVhlyr8cJpKpwG3gDFYD7Xrugm2dMZjYRHh9M    # Your OIDC Issuer's Client ID for Headscale-WebUI
      - OIDC_CLIENT_SECRET=ck5BcaK1WfuyktuYyVezAGrVc8r1lFEFgS8hA6ci2VBmLejXTkovfX9o4UQcGK98tfYfRpSxJJKwzerfOSkULLXaIUhBqosc4TgetJjbMCcudJvzKFse7urI1Z7mo3TJ     # Your OIDC Issuer's >
    ports:
      - 9290:5000
    volumes:
      - ./volume:/data                         # Headscale-WebUI's storage.  Make sure ./volume is readable by UID 1000 (chown 1000:1000 ./volume)
      - ./config/:/etc/headscale/:ro # Headscale's config storage location.  Used to read your Headscale config.

